--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MagmaZ3637/MTrim
build-by-default: true
branches:
- main
projects:
  MTrim:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: KRUNCHSHooT/LibTrimArmor/LibTrimArmor
        version: ^1.0.0
...
