--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MagmaZ3637/MTrims
build-by-default: true
branches:
- main
projects:
  MTrims:
    path: ""
    icon: "icon.png"
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: KRUNCHSHooT/LibTrimArmor/LibTrimArmor
        version: ^1.0.0
    lint:
     phpstan: false
...
