name: MTrim
api: 5.0.0
version: 1.0.0
main: MagmaZ3637\MTrim\Main
author: MagmaZ3637
description: A PocketMine-MP plugin that allows players to add trims to their armor using a UI.

commands:
  trim:
    permission: trim.use
    description: Open the armor trim UI for customization.

permissions:
  trim.use:
    default: true
    description: Allow player to use the trim command.
